[package]
name = "menu_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
