[package]
name = "menu_rs"
version = "0.2.0"
edition = "2021"
authors = ["NFSS10"]
description = "A simple command line menu"
license-file = "LICENSE"

[dependencies]
console = "0.15.2"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
